In [1]:
"""
Import USDA file with county typology data

Output to pickle
"""

'\nFilter data file with population data from USDA to year 2019.\nPivot table from tall to wide.\n\nOutput to pickle\n'

In [2]:
import pandas as pd
import numpy as np
import pickle

In [4]:
cnty_typol = pd.read_csv('../data/2015CountyTypologyCodes.csv', encoding='unicode-escape')
cnty_typol.shape

(3143, 18)

In [5]:
cnty_typol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 18 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   FIPStxt                                          3143 non-null   int64
 1   State                                            3143 non-null   object
 2   County_name                                      3143 non-null   object
 3   Metro-nonmetro status, 2013 0=Nonmetro 1=Metro   3143 non-null   int64
 4   Economic Types Type_2015_Update non-overlapping  3143 non-null   int64
 5   Economic_Type_Label                              3143 non-null   object
 6   Farming_2015_Update                              3143 non-null   int64
 7   Mining_2015-Update                               3143 non-null   int64
 8   Manufacturing_2015_Update                        3143 non-null   int64
 9   Government_2015_Update                           3143 non-null   int64
 10  Recreation_2015_Update                           3143 non-null   int64
 11  Nonspecialized_2015_Update                       3143 non-null   int64
 12  Low_Education_2015_Update                        3143 non-null   int64
 13  Low_Employment_Cnty_2008_2012_25_64              3143 non-null   int64
 14  Pop_Loss_2010                                    3143 non-null   int64
 15  Retirement_Dest_2015_Update                      3143 non-null   int64
 16  Persistent_Poverty_2013                          3143 non-null   int64
 17  Persistent_Related_Child_Poverty_2013            3143 non-null   int64
dtypes: int64(15), object(3)
memory usage: 442.1+ KB

In [7]:
cnty_typol.head(10)

,FIPStxt,State,County_name,"Metro-nonmetro status, 2013 0=Nonmetro 1=Metro",Economic Types Type_2015_Update non-overlapping,Economic_Type_Label,Farming_2015_Update,Mining_2015-Update,Manufacturing_2015_Update,Government_2015_Update,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Pop_Loss_2010,Retirement_Dest_2015_Update,Persistent_Poverty_2013,Persistent_Related_Child_Poverty_2013
0,1001,AL,Autauga County,1,0,Nonspecialized,0,0,0,0,0,1,0,0,0,1,0,0
1,1003,AL,Baldwin County,1,5,Recreation,0,0,0,0,1,0,0,0,0,1,0,0
2,1005,AL,Barbour County,0,3,Maufacturing,0,0,1,0,0,0,1,1,0,0,1,1
3,1007,AL,Bibb County,1,0,Nonspecialized,0,0,0,0,0,1,1,1,0,0,0,1
4,1009,AL,Blount County,1,0,Nonspecialized,0,0,0,0,0,1,1,1,0,0,0,0
5,1011,AL,Bullock County,0,3,Maufacturing,0,0,1,1,0,0,1,1,0,0,1,1
6,1013,AL,Butler County,0,0,Nonspecialized,0,0,0,0,0,1,0,1,1,0,1,1
7,1015,AL,Calhoun County,1,4,Federal/State Government,0,0,0,1,0,0,0,1,0,0,0,0
8,1017,AL,Chambers County,0,0,Nonspecialized,0,0,0,0,0,1,1,1,1,0,0,1
9,1019,AL,Cherokee County,0,0,Nonspecialized,0,0,0,0,0,1,0,1,0,0,0,0

In [8]:
cnty_typol.columns

Index(['FIPStxt', 'State', 'County_name',
       'Metro-nonmetro status, 2013 0=Nonmetro 1=Metro',
       'Economic Types Type_2015_Update non-overlapping',
       'Economic_Type_Label', 'Farming_2015_Update', 'Mining_2015-Update',
       'Manufacturing_2015_Update', 'Government_2015_Update',
       'Recreation_2015_Update', 'Nonspecialized_2015_Update',
       'Low_Education_2015_Update', 'Low_Employment_Cnty_2008_2012_25_64',
       'Pop_Loss_2010', 'Retirement_Dest_2015_Update',
       'Persistent_Poverty_2013', 'Persistent_Related_Child_Poverty_2013'],
      dtype='object')

In [11]:
with open('county_typology.pickle', 'wb') as to_write:
    pickle.dump(cnty_typol, to_write)