In [ ]:
"""
prepare df for model

review data for any needed cleaning 

target: Median_HH_Income_2019

"""

In [55]:
import pickle
import pandas as pd
import numpy as np

In [56]:
with open('county_data.pickle', 'rb') as read_file:
    county_data = pickle.load(read_file)
    
county_data.head()

,fips_txt,Stabr,area_name,Civilian_labor_force_2019,Employed_2019,Med_HH_Income_Percent_of_State_Total_2019,Median_Household_Income_2019,Metro_2013,Rural_urban_continuum_code_2013,Unemployed_2019,...,county_page_url,highways,hwy_count,cities,city_count,towns,town_count,abbr,FIPS,FIPS_code_NEW
0,1001,AL,"Autauga County, AL",26172.0,25458.0,112.481888,58233.0,1.0,2.0,714.0,...,"https://en.wikipedia.org/wiki/Autauga_County,_...","[Interstate 65, U.S. Highway 31, U.S. Highway ...",6.0,"[Millbrook, Prattville]",2.0,"[Autaugaville, Billingsley]",2.0,AL,01,01001
1,1003,AL,"Baldwin County, AL",97328.0,94675.0,115.645828,59871.0,1.0,3.0,2653.0,...,"https://en.wikipedia.org/wiki/Baldwin_County,_...","[Interstate 10, Interstate 65, U.S. Highway 31...",12.0,"[Bay Minette, Daphne, Fairhope, Foley, Gulf Sh...",8.0,"[Elberta, Loxley, Magnolia Springs, Perdido Be...",6.0,AL,01,01003
2,1005,AL,"Barbour County, AL",8537.0,8213.0,69.482918,35972.0,0.0,6.0,324.0,...,"https://en.wikipedia.org/wiki/Barbour_County,_...","[U.S. Highway 82, U.S. Highway 431, State Rout...",11.0,"[Clio, Eufaula]",2.0,"[Bakerhill, Blue Springs, Clayton, Louisville]",4.0,AL,01,01005
3,1007,AL,"Bibb County, AL",8685.0,8419.0,92.557610,47918.0,1.0,1.0,266.0,...,"https://en.wikipedia.org/wiki/Bibb_County,_Ala...","[U.S. Highway 11, U.S. Highway 82, State Route...",8.0,"[Brent, Centreville]",2.0,"[Vance, West Blocton, Woodstock]",3.0,AL,01,01007
4,1009,AL,"Blount County, AL",25331.0,24655.0,102.184624,52902.0,1.0,1.0,676.0,...,"https://en.wikipedia.org/wiki/Blount_County,_A...","[Interstate 65, U.S. Highway 31, U.S. Highway ...",9.0,"[Oneonta, Warrior]",2.0,"[Allgood, Altoona, Blountsville, Cleveland, Co...",14.0,AL,01,01009

In [57]:
len(county_data)

3144

In [58]:
county_data.columns

Index(['fips_txt', 'Stabr', 'area_name', 'Civilian_labor_force_2019',
       'Employed_2019', 'Med_HH_Income_Percent_of_State_Total_2019',
       'Median_Household_Income_2019', 'Metro_2013',
       'Rural_urban_continuum_code_2013', 'Unemployed_2019',
       'Unemployment_rate_2019', 'Urban_influence_code_2013', 'FIPS_code_x',
       'FIPStxt_x', 'State_x', 'Area_Name', 'POP_ESTIMATE_2019',
       'N_POP_CHG_2019', 'FIPStxt_y', 'State_y', 'County_name',
       'Metro-nonmetro status, 2013 0=Nonmetro 1=Metro',
       'Economic Types Type_2015_Update non-overlapping',
       'Economic_Type_Label', 'Farming_2015_Update', 'Mining_2015-Update',
       'Manufacturing_2015_Update', 'Government_2015_Update',
       'Recreation_2015_Update', 'Nonspecialized_2015_Update',
       'Low_Education_2015_Update', 'Low_Employment_Cnty_2008_2012_25_64',
       'Pop_Loss_2010', 'Retirement_Dest_2015_Update',
       'Persistent_Poverty_2013', 'Persistent_Related_Child_Poverty_2013',
       'state', 'county_name', 'FIPS_code_y', 'county_page_url', 'highways',
       'hwy_count', 'cities', 'city_count', 'towns', 'town_count', 'abbr',
       'FIPS', 'FIPS_code_NEW'],
      dtype='object')

In [63]:
cnty_data = county_data[['fips_txt',
                        'FIPS_code_NEW',  #ST FIPS + County FIPS
                       'Stabr',  # ST abbreviation
                       'area_name',   # county, ST
                       'Area_Name',   # county
                         
                       'Median_Household_Income_2019',  # target
                         
                       'POP_ESTIMATE_2019', 
                         
                       'Civilian_labor_force_2019',
                       'Employed_2019', 
                       'Unemployed_2019',
                       'Unemployment_rate_2019', 

                       'Metro_2013',
                       'Rural_urban_continuum_code_2013',   
           
                       'Farming_2015_Update', 
                       'Mining_2015-Update',
                       'Manufacturing_2015_Update', 
                       'Government_2015_Update',
                       'Recreation_2015_Update', 
                       'Nonspecialized_2015_Update',
                         
                       'Low_Education_2015_Update', 
                       'Low_Employment_Cnty_2008_2012_25_64', 
                        
                        'Retirement_Dest_2015_Update',
                        'Persistent_Poverty_2013', 
                         
                        'hwy_count',
                        'city_count',
                        'town_count' ]]

In [64]:
cnty_data.head()

,fips_txt,FIPS_code_NEW,Stabr,area_name,Area_Name,Median_Household_Income_2019,POP_ESTIMATE_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,...,Government_2015_Update,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013,hwy_count,city_count,town_count
0,1001,01001,AL,"Autauga County, AL",Autauga County,58233.0,"55,869",26172.0,25458.0,714.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,6.0,2.0,2.0
1,1003,01003,AL,"Baldwin County, AL",Baldwin County,59871.0,"223,234",97328.0,94675.0,2653.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,12.0,8.0,6.0
2,1005,01005,AL,"Barbour County, AL",Barbour County,35972.0,"24,686",8537.0,8213.0,324.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,11.0,2.0,4.0
3,1007,01007,AL,"Bibb County, AL",Bibb County,47918.0,"22,394",8685.0,8419.0,266.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,8.0,2.0,3.0
4,1009,01009,AL,"Blount County, AL",Blount County,52902.0,"57,826",25331.0,24655.0,676.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,9.0,2.0,14.0

In [65]:
# review for any null 

cnty_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3144 entries, 0 to 3143
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fips_txt                             3144 non-null   object
 1   FIPS_code_NEW                        3092 non-null   object
 2   Stabr                                3144 non-null   object
 3   area_name                            3144 non-null   object
 4   Area_Name                            3141 non-null   object
 5   Median_Household_Income_2019         3141 non-null   float64
 6   POP_ESTIMATE_2019                    3141 non-null   object
 7   Civilian_labor_force_2019            3141 non-null   float64
 8   Employed_2019                        3141 non-null   float64
 9   Unemployed_2019                      3141 non-null   float64
 10  Unemployment_rate_2019               3141 non-null   float64
 11  Metro_2013                           3144 non-null   float64
 12  Rural_urban_continuum_code_2013      3141 non-null   float64
 13  Farming_2015_Update                  3139 non-null   float64
 14  Mining_2015-Update                   3139 non-null   float64
 15  Manufacturing_2015_Update            3139 non-null   float64
 16  Government_2015_Update               3139 non-null   float64
 17  Recreation_2015_Update               3139 non-null   float64
 18  Nonspecialized_2015_Update           3139 non-null   float64
 19  Low_Education_2015_Update            3139 non-null   float64
 20  Low_Employment_Cnty_2008_2012_25_64  3139 non-null   float64
 21  Retirement_Dest_2015_Update          3139 non-null   float64
 22  Persistent_Poverty_2013              3139 non-null   float64
 23  hwy_count                            3092 non-null   float64
 24  city_count                           3092 non-null   float64
 25  town_count                           3092 non-null   float64
dtypes: float64(20), object(6)
memory usage: 663.2+ KB

In [66]:
cnty_data[cnty_data['FIPS_code_NEW'].isna()]

,fips_txt,FIPS_code_NEW,Stabr,area_name,Area_Name,Median_Household_Income_2019,POP_ESTIMATE_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,...,Government_2015_Update,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013,hwy_count,city_count,town_count
68,2016,NaN,AK,"Aleutians West Census Area, AK",Aleutians West Census Area,84726.0,"5,634",3606.0,3477.0,129.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
70,2050,NaN,AK,"Bethel Census Area, AK",Bethel Census Area,48262.0,"18,386",7025.0,6120.0,905.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN
73,2070,NaN,AK,"Dillingham Census Area, AK",Dillingham Census Area,57436.0,"4,916",1938.0,1781.0,157.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
76,2105,NaN,AK,"Hoonah-Angoon Census Area, AK",Hoonah-Angoon Census Area,53141.0,"2,148",1160.0,1028.0,132.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
81,2158,NaN,AK,"Kusilvak Census Area, AK",Kusilvak Census Area,35369.0,"8,314",2682.0,2164.0,518.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,2180,NaN,AK,"Nome Census Area, AK",Nome Census Area,58464.0,"10,004",4036.0,3596.0,440.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN
88,2198,NaN,AK,"Prince of Wales-Hyder Census Area, AK",Prince of Wales-Hyder Census Area,50049.0,"6,203",2851.0,2562.0,289.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
89,2201,NaN,AK,"Prince of Wales-Outer Ketchikan Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2232,NaN,AK,"Skagway-Hoonah-Angoon Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,2240,NaN,AK,"Southeast Fairbanks Census Area, AK",Southeast Fairbanks Census Area,69646.0,"6,893",2810.0,2558.0,252.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
94,2261,NaN,AK,"Valdez-Cordova Census Area, AK",Valdez-Cordova Census Area,74574.0,"9,202",4815.0,4452.0,363.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
96,2280,NaN,AK,"Wrangell-Petersburg Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2290,NaN,AK,"Yukon-Koyukuk Census Area, AK",Yukon-Koyukuk Census Area,42063.0,"5,230",2458.0,2113.0,345.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
322,11001,NaN,DC,District of Columbia,District of Columbia,90395.0,"705,749",409969.0,387482.0,22487.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2917,51510,NaN,VA,"Alexandria city, VA",Alexandria city,102589.0,"159,428",102254.0,100093.0,2161.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2918,51520,NaN,VA,"Bristol city, VA",Bristol city,37678.0,"16,762",7218.0,6946.0,272.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2919,51530,NaN,VA,"Buena Vista city, VA",Buena Vista city,44752.0,"6,478",3436.0,3342.0,94.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2920,51540,NaN,VA,"Charlottesville city, VA",Charlottesville city,58717.0,"47,266",26642.0,26011.0,631.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2921,51550,NaN,VA,"Chesapeake city, VA",Chesapeake city,77361.0,"244,835",123523.0,119957.0,3566.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2922,51570,NaN,VA,"Colonial Heights city, VA",Colonial Heights city,57688.0,"17,370",8877.0,8593.0,284.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2923,51580,NaN,VA,"Covington city, VA",Covington city,41842.0,"5,538",2393.0,2293.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2924,51590,NaN,VA,"Danville city, VA",Danville city,36073.0,"40,044",19226.0,18261.0,965.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2925,51595,NaN,VA,"Emporia city, VA",Emporia city,38631.0,"5,346",2303.0,2189.0,114.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN
2926,51600,NaN,VA,"Fairfax city, VA",Fairfax city,106430.0,"24,019",13573.0,13284.0,289.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2927,51610,NaN,VA,"Falls Church city, VA",Falls Church city,137849.0,"14,617",8676.0,8499.0,177.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2928,51620,NaN,VA,"Franklin city, VA",Franklin city,45433.0,"7,967",3598.0,3453.0,145.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN
2929,51630,NaN,VA,"Fredericksburg city, VA",Fredericksburg city,62121.0,"29,036",14282.0,13803.0,479.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2930,51640,NaN,VA,"Galax city, VA",Galax city,37229.0,"6,347",2932.0,2836.0,96.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2931,51650,NaN,VA,"Hampton city, VA",Hampton city,55816.0,"134,510",64807.0,62353.0,2454.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2932,51660,NaN,VA,"Harrisonburg city, VA",Harrisonburg city,48189.0,"53,016",25153.0,24345.0,808.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2933,51670,NaN,VA,"Hopewell city, VA",Hopewell city,38293.0,"22,529",9757.0,9341.0,416.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN
2934,51678,NaN,VA,"Lexington city, VA",Lexington city,54204.0,"7,446",2099.0,2001.0,98.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2935,51680,NaN,VA,"Lynchburg city, VA",Lynchburg city,50612.0,"82,168",36598.0,35238.0,1360.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2936,51683,NaN,VA,"Manassas city, VA",Manassas city,84405.0,"41,085",22253.0,21696.0,557.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2937,51685,NaN,VA,"Manassas Park city, VA",Manassas Park city,83145.0,"17,478",9462.0,9228.0,234.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2938,51690,NaN,VA,"Martinsville city, VA",Martinsville city,37814.0,"12,554",5501.0,5274.0,227.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN
2939,51700,NaN,VA,"Newport News city, VA",Newport News city,53022.0,"179,225",89406.0,86310.0,3096.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2940,51710,NaN,VA,"Norfolk city, VA",Norfolk city,52437.0,"242,742",112364.0,108487.0,3877.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2941,51720,NaN,VA,"Norton city, VA",Norton city,38062.0,"3,981",1687.0,1625.0,62.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN
2942,51730,NaN,VA,"Petersburg city, VA",Petersburg city,40240.0,"31,346",13129.0,12396.0,733.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN
2943,51735,NaN,VA,"Poquoson city, VA",Poquoson city,98217.0,"12,271",6427.0,6271.0,156.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2944,51740,NaN,VA,"Portsmouth city, VA",Portsmouth city,50411.0,"94,398",44566.0,42831.0,1735.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2945,51750,NaN,VA,"Radford city, VA",Radford city,41530.0,"18,249",8688.0,8377.0,311.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2946,51760,NaN,VA,"Richmond city, VA",Richmond city,50949.0,"230,436",119265.0,115360.0,3905.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2947,51770,NaN,VA,"Roanoke city, VA",Roanoke city,45534.0,"99,143",49397.0,47900.0,1497.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2948,51775,NaN,VA,"Salem city, VA",Salem city,54888.0,"25,301",13037.0,12677.0,360.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2949,51790,NaN,VA,"Staunton city, VA",Staunton city,54296.0,"24,932",12314.0,11986.0,328.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2950,51800,NaN,VA,"Suffolk city, VA",Suffolk city,77847.0,"92,108",44928.0,43564.0,1364.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2951,51810,NaN,VA,"Virginia Beach city, VA",Virginia Beach city,78491.0,"449,974",234597.0,228266.0,6331.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2952,51820,NaN,VA,"Waynesboro city, VA",Waynesboro city,44619.0,"22,630",10762.0,10451.0,311.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2953,51830,NaN,VA,"Williamsburg city, VA",Williamsburg city,56569.0,"14,954",6736.0,6475.0,261.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2954,51840,NaN,VA,"Winchester city, VA",Winchester city,60254.0,"28,078",14892.0,14480.0,412.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN

In [68]:
cnty_data['FIPS_code'] = cnty_data['fips_txt'].apply(lambda x: str(x).zfill(5))

<ipython-input-68-989a5441b323>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cnty_data['FIPS_code'] = cnty_data['fips_txt'].apply(lambda x: str(x).zfill(5))

In [69]:
cnty_data[cnty_data['hwy_count'].isna()]

,fips_txt,FIPS_code_NEW,Stabr,area_name,Area_Name,Median_Household_Income_2019,POP_ESTIMATE_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,...,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013,hwy_count,city_count,town_count,FIPS_code
68,2016,NaN,AK,"Aleutians West Census Area, AK",Aleutians West Census Area,84726.0,"5,634",3606.0,3477.0,129.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,02016
70,2050,NaN,AK,"Bethel Census Area, AK",Bethel Census Area,48262.0,"18,386",7025.0,6120.0,905.0,...,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,02050
73,2070,NaN,AK,"Dillingham Census Area, AK",Dillingham Census Area,57436.0,"4,916",1938.0,1781.0,157.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,02070
76,2105,NaN,AK,"Hoonah-Angoon Census Area, AK",Hoonah-Angoon Census Area,53141.0,"2,148",1160.0,1028.0,132.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,02105
81,2158,NaN,AK,"Kusilvak Census Area, AK",Kusilvak Census Area,35369.0,"8,314",2682.0,2164.0,518.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02158
84,2180,NaN,AK,"Nome Census Area, AK",Nome Census Area,58464.0,"10,004",4036.0,3596.0,440.0,...,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,02180
88,2198,NaN,AK,"Prince of Wales-Hyder Census Area, AK",Prince of Wales-Hyder Census Area,50049.0,"6,203",2851.0,2562.0,289.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,02198
89,2201,NaN,AK,"Prince of Wales-Outer Ketchikan Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02201
92,2232,NaN,AK,"Skagway-Hoonah-Angoon Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02232
93,2240,NaN,AK,"Southeast Fairbanks Census Area, AK",Southeast Fairbanks Census Area,69646.0,"6,893",2810.0,2558.0,252.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,02240
94,2261,NaN,AK,"Valdez-Cordova Census Area, AK",Valdez-Cordova Census Area,74574.0,"9,202",4815.0,4452.0,363.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,02261
96,2280,NaN,AK,"Wrangell-Petersburg Census Area, AK",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02280
98,2290,NaN,AK,"Yukon-Koyukuk Census Area, AK",Yukon-Koyukuk Census Area,42063.0,"5,230",2458.0,2113.0,345.0,...,0.0,1.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN,02290
322,11001,NaN,DC,District of Columbia,District of Columbia,90395.0,"705,749",409969.0,387482.0,22487.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,11001
2917,51510,NaN,VA,"Alexandria city, VA",Alexandria city,102589.0,"159,428",102254.0,100093.0,2161.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51510
2918,51520,NaN,VA,"Bristol city, VA",Bristol city,37678.0,"16,762",7218.0,6946.0,272.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51520
2919,51530,NaN,VA,"Buena Vista city, VA",Buena Vista city,44752.0,"6,478",3436.0,3342.0,94.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51530
2920,51540,NaN,VA,"Charlottesville city, VA",Charlottesville city,58717.0,"47,266",26642.0,26011.0,631.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51540
2921,51550,NaN,VA,"Chesapeake city, VA",Chesapeake city,77361.0,"244,835",123523.0,119957.0,3566.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51550
2922,51570,NaN,VA,"Colonial Heights city, VA",Colonial Heights city,57688.0,"17,370",8877.0,8593.0,284.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51570
2923,51580,NaN,VA,"Covington city, VA",Covington city,41842.0,"5,538",2393.0,2293.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51580
2924,51590,NaN,VA,"Danville city, VA",Danville city,36073.0,"40,044",19226.0,18261.0,965.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51590
2925,51595,NaN,VA,"Emporia city, VA",Emporia city,38631.0,"5,346",2303.0,2189.0,114.0,...,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,51595
2926,51600,NaN,VA,"Fairfax city, VA",Fairfax city,106430.0,"24,019",13573.0,13284.0,289.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51600
2927,51610,NaN,VA,"Falls Church city, VA",Falls Church city,137849.0,"14,617",8676.0,8499.0,177.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51610
2928,51620,NaN,VA,"Franklin city, VA",Franklin city,45433.0,"7,967",3598.0,3453.0,145.0,...,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,51620
2929,51630,NaN,VA,"Fredericksburg city, VA",Fredericksburg city,62121.0,"29,036",14282.0,13803.0,479.0,...,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,51630
2930,51640,NaN,VA,"Galax city, VA",Galax city,37229.0,"6,347",2932.0,2836.0,96.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51640
2931,51650,NaN,VA,"Hampton city, VA",Hampton city,55816.0,"134,510",64807.0,62353.0,2454.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51650
2932,51660,NaN,VA,"Harrisonburg city, VA",Harrisonburg city,48189.0,"53,016",25153.0,24345.0,808.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51660
2933,51670,NaN,VA,"Hopewell city, VA",Hopewell city,38293.0,"22,529",9757.0,9341.0,416.0,...,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,51670
2934,51678,NaN,VA,"Lexington city, VA",Lexington city,54204.0,"7,446",2099.0,2001.0,98.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51678
2935,51680,NaN,VA,"Lynchburg city, VA",Lynchburg city,50612.0,"82,168",36598.0,35238.0,1360.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51680
2936,51683,NaN,VA,"Manassas city, VA",Manassas city,84405.0,"41,085",22253.0,21696.0,557.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51683
2937,51685,NaN,VA,"Manassas Park city, VA",Manassas Park city,83145.0,"17,478",9462.0,9228.0,234.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51685
2938,51690,NaN,VA,"Martinsville city, VA",Martinsville city,37814.0,"12,554",5501.0,5274.0,227.0,...,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,51690
2939,51700,NaN,VA,"Newport News city, VA",Newport News city,53022.0,"179,225",89406.0,86310.0,3096.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51700
2940,51710,NaN,VA,"Norfolk city, VA",Norfolk city,52437.0,"242,742",112364.0,108487.0,3877.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51710
2941,51720,NaN,VA,"Norton city, VA",Norton city,38062.0,"3,981",1687.0,1625.0,62.0,...,0.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,51720
2942,51730,NaN,VA,"Petersburg city, VA",Petersburg city,40240.0,"31,346",13129.0,12396.0,733.0,...,0.0,1.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,51730
2943,51735,NaN,VA,"Poquoson city, VA",Poquoson city,98217.0,"12,271",6427.0,6271.0,156.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51735
2944,51740,NaN,VA,"Portsmouth city, VA",Portsmouth city,50411.0,"94,398",44566.0,42831.0,1735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51740
2945,51750,NaN,VA,"Radford city, VA",Radford city,41530.0,"18,249",8688.0,8377.0,311.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51750
2946,51760,NaN,VA,"Richmond city, VA",Richmond city,50949.0,"230,436",119265.0,115360.0,3905.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51760
2947,51770,NaN,VA,"Roanoke city, VA",Roanoke city,45534.0,"99,143",49397.0,47900.0,1497.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51770
2948,51775,NaN,VA,"Salem city, VA",Salem city,54888.0,"25,301",13037.0,12677.0,360.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51775
2949,51790,NaN,VA,"Staunton city, VA",Staunton city,54296.0,"24,932",12314.0,11986.0,328.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51790
2950,51800,NaN,VA,"Suffolk city, VA",Suffolk city,77847.0,"92,108",44928.0,43564.0,1364.0,...,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,51800
2951,51810,NaN,VA,"Virginia Beach city, VA",Virginia Beach city,78491.0,"449,974",234597.0,228266.0,6331.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51810
2952,51820,NaN,VA,"Waynesboro city, VA",Waynesboro city,44619.0,"22,630",10762.0,10451.0,311.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,51820
2953,51830,NaN,VA,"Williamsburg city, VA",Williamsburg city,56569.0,"14,954",6736.0,6475.0,261.0,...,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,51830
2954,51840,NaN,VA,"Winchester city, VA",Winchester city,60254.0,"28,078",14892.0,14480.0,412.0,...,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,51840

In [70]:
# one of the data sources contained census areas for AK in addition to counties
# Also VA independent cities 
# add in 0 for DC hwy, towns, cities

# research these features for the additional areas of VA and AK time-permitting

cnty_data.loc[cnty_data['Stabr'] == 'DC', ['hwy_count', 'city_count', 'town_count']] = 0
cnty_data.loc[cnty_data['Stabr'] == 'DC', ['FIPS_code_NEW']] = '11001'

cnty_data.loc[cnty_data['Stabr'] == 'DC']

/Users/amybutler/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1719: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,fips_txt,FIPS_code_NEW,Stabr,area_name,Area_Name,Median_Household_Income_2019,POP_ESTIMATE_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,...,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013,hwy_count,city_count,town_count,FIPS_code
322,11001,11001,DC,District of Columbia,District of Columbia,90395.0,"705,749",409969.0,387482.0,22487.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11001

In [71]:
model_data = cnty_data.dropna()

model_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3092 entries, 0 to 3143
Data columns (total 27 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fips_txt                             3092 non-null   object
 1   FIPS_code_NEW                        3092 non-null   object
 2   Stabr                                3092 non-null   object
 3   area_name                            3092 non-null   object
 4   Area_Name                            3092 non-null   object
 5   Median_Household_Income_2019         3092 non-null   float64
 6   POP_ESTIMATE_2019                    3092 non-null   object
 7   Civilian_labor_force_2019            3092 non-null   float64
 8   Employed_2019                        3092 non-null   float64
 9   Unemployed_2019                      3092 non-null   float64
 10  Unemployment_rate_2019               3092 non-null   float64
 11  Metro_2013                           3092 non-null   float64
 12  Rural_urban_continuum_code_2013      3092 non-null   float64
 13  Farming_2015_Update                  3092 non-null   float64
 14  Mining_2015-Update                   3092 non-null   float64
 15  Manufacturing_2015_Update            3092 non-null   float64
 16  Government_2015_Update               3092 non-null   float64
 17  Recreation_2015_Update               3092 non-null   float64
 18  Nonspecialized_2015_Update           3092 non-null   float64
 19  Low_Education_2015_Update            3092 non-null   float64
 20  Low_Employment_Cnty_2008_2012_25_64  3092 non-null   float64
 21  Retirement_Dest_2015_Update          3092 non-null   float64
 22  Persistent_Poverty_2013              3092 non-null   float64
 23  hwy_count                            3092 non-null   float64
 24  city_count                           3092 non-null   float64
 25  town_count                           3092 non-null   float64
 26  FIPS_code                            3092 non-null   object
dtypes: float64(20), object(7)
memory usage: 676.4+ KB

In [72]:
# pop_estimate_2019 needs converted to number
model_data['pop_est_2019'] = model_data['POP_ESTIMATE_2019'].str.replace(',','').astype(float)

<ipython-input-72-56a3fe91a983>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_data['pop_est_2019'] = model_data['POP_ESTIMATE_2019'].str.replace(',','').astype(float)

In [73]:
model_data['pop_est_2019']

0        55869.0
1       223234.0
2        24686.0
3        22394.0
4        57826.0
          ...
3139     42343.0
3140     23464.0
3141     20226.0
3142      7805.0
3143      6927.0
Name: pop_est_2019, Length: 3092, dtype: float64

In [74]:
model_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3092 entries, 0 to 3143
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fips_txt                             3092 non-null   object
 1   FIPS_code_NEW                        3092 non-null   object
 2   Stabr                                3092 non-null   object
 3   area_name                            3092 non-null   object
 4   Area_Name                            3092 non-null   object
 5   Median_Household_Income_2019         3092 non-null   float64
 6   POP_ESTIMATE_2019                    3092 non-null   object
 7   Civilian_labor_force_2019            3092 non-null   float64
 8   Employed_2019                        3092 non-null   float64
 9   Unemployed_2019                      3092 non-null   float64
 10  Unemployment_rate_2019               3092 non-null   float64
 11  Metro_2013                           3092 non-null   float64
 12  Rural_urban_continuum_code_2013      3092 non-null   float64
 13  Farming_2015_Update                  3092 non-null   float64
 14  Mining_2015-Update                   3092 non-null   float64
 15  Manufacturing_2015_Update            3092 non-null   float64
 16  Government_2015_Update               3092 non-null   float64
 17  Recreation_2015_Update               3092 non-null   float64
 18  Nonspecialized_2015_Update           3092 non-null   float64
 19  Low_Education_2015_Update            3092 non-null   float64
 20  Low_Employment_Cnty_2008_2012_25_64  3092 non-null   float64
 21  Retirement_Dest_2015_Update          3092 non-null   float64
 22  Persistent_Poverty_2013              3092 non-null   float64
 23  hwy_count                            3092 non-null   float64
 24  city_count                           3092 non-null   float64
 25  town_count                           3092 non-null   float64
 26  FIPS_code                            3092 non-null   object
 27  pop_est_2019                         3092 non-null   float64
dtypes: float64(21), object(7)
memory usage: 700.5+ KB

In [75]:
min(model_data['Median_Household_Income_2019'])

24732.0

In [76]:
max(model_data['Median_Household_Income_2019'])

151806.0

In [77]:
#model_data[model_data['Stabr']=='AK']
# 19 organized boroughs in AK

,fips_txt,FIPS_code_NEW,Stabr,area_name,Area_Name,Median_Household_Income_2019,POP_ESTIMATE_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,...,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013,hwy_count,city_count,town_count,FIPS_code,pop_est_2019
67,2013,02013,AK,"Aleutians East Borough, AK",Aleutians East Borough,66923.0,"3,337",2428.0,2360.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,02013,3337.0
69,2020,02020,AK,"Anchorage Borough/municipality, AK",Anchorage Municipality,82512.0,"288,000",146949.0,139526.0,7423.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,02020,288000.0
71,2060,02060,AK,"Bristol Bay Borough, AK",Bristol Bay Borough,87950.0,836,441.0,414.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,02060,836.0
72,2068,02068,AK,"Denali Borough, AK",Denali Borough,78434.0,"2,097",1038.0,950.0,88.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,02068,2097.0
74,2090,02090,AK,"Fairbanks North Star Borough, AK",Fairbanks North Star Borough,74076.0,"96,849",44652.0,42248.0,2404.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,02090,96849.0
75,2100,02100,AK,"Haines Borough, AK",Haines Borough,62548.0,"2,530",1111.0,1012.0,99.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,02100,2530.0
77,2110,02110,AK,"Juneau Borough/city, AK",Juneau City and Borough,85419.0,"31,974",16999.0,16243.0,756.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,02110,31974.0
78,2122,02122,AK,"Kenai Peninsula Borough, AK",Kenai Peninsula Borough,68625.0,"58,708",26161.0,24383.0,1778.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,02122,58708.0
79,2130,02130,AK,"Ketchikan Gateway Borough, AK",Ketchikan Gateway Borough,75706.0,"13,901",6884.0,6456.0,428.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,02130,13901.0
80,2150,02150,AK,"Kodiak Island Borough, AK",Kodiak Island Borough,79669.0,"12,998",5912.0,5582.0,330.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,02150,12998.0
82,2164,02164,AK,"Lake and Peninsula Borough, AK",Lake and Peninsula Borough,51693.0,"1,592",708.0,638.0,70.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,02164,1592.0
83,2170,02170,AK,"Matanuska-Susitna Borough, AK",Matanuska-Susitna Borough,75856.0,"108,317",46901.0,43661.0,3240.0,...,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,02170,108317.0
85,2185,02185,AK,"North Slope Borough, AK",North Slope Borough,84784.0,"9,832",3485.0,3261.0,224.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,02185,9832.0
86,2188,02188,AK,"Northwest Arctic Borough, AK",Northwest Arctic Borough,61660.0,"7,621",2934.0,2523.0,411.0,...,0.0,0.0,1.0,0.0,0.0,0.0,10.0,0.0,02188,7621.0
87,2195,02195,AK,"Petersburg Borough, AK",Petersburg Borough,71296.0,"3,266",1388.0,1267.0,121.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,02195,3266.0
90,2220,02220,AK,"Sitka Borough/city, AK",Sitka City and Borough,80660.0,"8,493",4336.0,4155.0,181.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,02220,8493.0
91,2230,02230,AK,"Skagway Municipality, AK",Skagway Municipality,74898.0,"1,183",822.0,746.0,76.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,02230,1183.0
95,2275,02275,AK,"Wrangell Borough/city, AK",Wrangell City and Borough,62496.0,"2,502",1002.0,925.0,77.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,02275,2502.0
97,2282,02282,AK,"Yakutat Borough/city, AK",Yakutat City and Borough,61587.0,579,246.0,227.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,02282,579.0

In [81]:
# drop columns not needed 
model_data.drop(['fips_txt', 'FIPS_code_NEW', 'POP_ESTIMATE_2019'], axis=1, inplace=True)

/Users/amybutler/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4305: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [82]:
model_data.columns

Index(['Stabr', 'area_name', 'Area_Name', 'Median_Household_Income_2019',
       'Civilian_labor_force_2019', 'Employed_2019', 'Unemployed_2019',
       'Unemployment_rate_2019', 'Metro_2013',
       'Rural_urban_continuum_code_2013', 'Farming_2015_Update',
       'Mining_2015-Update', 'Manufacturing_2015_Update',
       'Government_2015_Update', 'Recreation_2015_Update',
       'Nonspecialized_2015_Update', 'Low_Education_2015_Update',
       'Low_Employment_Cnty_2008_2012_25_64', 'Retirement_Dest_2015_Update',
       'Persistent_Poverty_2013', 'hwy_count', 'city_count', 'town_count',
       'FIPS_code', 'pop_est_2019'],
      dtype='object')

In [83]:
# reorder columns for easy splitting into ranges for eda and model

eda_ready = model_data[[ 
                        # county/area identifiers
                        'FIPS_code','Stabr', 'area_name', 'Area_Name', 
                        
                        # target
                        'Median_Household_Income_2019', 
                        
                        # numeric features
                        'pop_est_2019', 'Civilian_labor_force_2019', 'Employed_2019', 
                        'Unemployed_2019', 'Unemployment_rate_2019', 
                        'hwy_count', 'city_count', 'town_count',
                        
                        # category features
                       'Metro_2013',
                       'Rural_urban_continuum_code_2013', 'Farming_2015_Update',
                       'Mining_2015-Update', 'Manufacturing_2015_Update',
                       'Government_2015_Update', 'Recreation_2015_Update',
                       'Nonspecialized_2015_Update', 'Low_Education_2015_Update',
                       'Low_Employment_Cnty_2008_2012_25_64', 'Retirement_Dest_2015_Update',
                       'Persistent_Poverty_2013' ]]

In [84]:
eda_ready.head()

,FIPS_code,Stabr,area_name,Area_Name,Median_Household_Income_2019,pop_est_2019,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,Unemployment_rate_2019,...,Farming_2015_Update,Mining_2015-Update,Manufacturing_2015_Update,Government_2015_Update,Recreation_2015_Update,Nonspecialized_2015_Update,Low_Education_2015_Update,Low_Employment_Cnty_2008_2012_25_64,Retirement_Dest_2015_Update,Persistent_Poverty_2013
0,01001,AL,"Autauga County, AL",Autauga County,58233.0,55869.0,26172.0,25458.0,714.0,2.7,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,01003,AL,"Baldwin County, AL",Baldwin County,59871.0,223234.0,97328.0,94675.0,2653.0,2.7,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,01005,AL,"Barbour County, AL",Barbour County,35972.0,24686.0,8537.0,8213.0,324.0,3.8,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,01007,AL,"Bibb County, AL",Bibb County,47918.0,22394.0,8685.0,8419.0,266.0,3.1,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
4,01009,AL,"Blount County, AL",Blount County,52902.0,57826.0,25331.0,24655.0,676.0,2.7,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [85]:
# review
model_data.to_excel('review_model_data.xlsx', index=False)

In [86]:
with open('county_eda_data.pickle', 'wb') as to_write:
    pickle.dump(eda_ready, to_write)